num1= input("Enter the first number:")
num2 = input("Enter the second number:")
add_num = float(num1) + float(num2)
sub_num = float(num1) - float(num2)
mul_num = float(num1) * float(num2)
div_num = float(num1) / float(num2)
print("Addition:",add_num)
print("Subtraction:",sub_num)
print("Multiplication:",mul_num)
print("Division:",div_num)
